### ISSUE TITLE
Build with ESP-IDF 4.4 fails

### ISSUE THREAD

**Issue by georgik** [Fabien-Chouteau/Ada_SPARK_on_ESP32C3_Demo#1]
Hi @Fabien-Chouteau .

Thank you for the great article: https://blog.adacore.com/embedded-ada-spark-theres-a-shortcut

I was trying the build. Unfortunately, the build failed. Please, can you confirm which version of ESP-IDF is used for the example?

Build with v4.4 fails with:
```
CMake Error at CMakeLists.txt:23 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "https_server.elf".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * .../projects/esp-idf-4.4/tools/cmake/project.cmake:456 (target_link_libraries)
   * .../projects/esp-idf-4.4/tools/cmake/project.cmake:460 (target_link_libraries)
 ```

**Comment by Fabien-Chouteau** [comment]
I am not sure, does this file means it's version 5.1: `.espressif/espidf.constraints.v5.1.txt` ?

**Comment by georgik** [comment]
Thank you @Fabien-Chouteau for the information. I'll try the build with 5.1.

The simplest way to verify ESP-IDF version is: `idf.py --version`

The constraints file name indicates Major and Minor version, it's same between patch releases.
